name: Go

on:
  push:
    branches: [ unit-test-case-fix ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    env:
      GO111MODULE: off
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...
