name: Go

on:
  push:
    branches: [ unit-test-case-fix ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    env:
      GO111MODULE: off
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Dependencies Installation
      run: |
        go get github.com/google/go-querystring/query
        go get github.com/sirupsen/logrus
        go get github.com/stretchr/testify/assert
    - name: Test
      run: go test -v ./...
